services:
  crawl:
    container_name: lasso_python_crawl
    build:
      context: ./backend/crawl
    ports:
      - "8010:8000"
    environment:
      - DOCKER=test
      - INSTALLED=/crawl/installed
      - INDEX=/crawl/index.json
      - RUNTIME=/arena/runtime
      - CORPUS=/nexus/corpus_docker.json
      - TYPE_INFERENCING_TEMP=/crawl/temp
      - SOLR_PATH=http://lasso_solr_quickstart:8983/solr/
      - NEXUS_HOST=http://nexus:8081
    volumes:
      - ./backend/crawl/installed:/crawl/installed
      - ./backend/crawl/index.json:/crawl/index.json
      - ./backend/crawl/temp:/crawl/temp
      - ./nexus/corpus.json:/nexus/corpus_docker.json
      - ./arena/runtime:/arena/runtime
  #app:
  #  container_name: lasso_python
  #  build:
  #    context: ./backend
  #  ports:
  #    - "8000:8000"
  #  environment:
  #    - DOCKER=test
  #    - SOLR_PATH=http://lasso_solr_quickstart:8983/solr/
  lasso_solr_quickstart:
    container_name: lasso_solr_quick
    image: solr:9.6.1
    ports:
      - "8983:8983"
    volumes:
      - ./lassoindex:/var/solr
    command:
      - solr-precreate
      - lasso_python
  nexus:
    container_name: lasso_nexus
    build:
      context: ./nexus
    ports:
      - "8081:8081"
  ignite:
    container_name: lasso_ignite
    image: apacheignite/ignite
    ports:
      - "10800:10800"