services:
  ignite:
    image: apacheignite/ignite
    container_name: lasso_ignite
    ports:
      - "10800:10800"
  lasso_solr_quickstart:
    image: solr:9.6.1
    container_name: lasso_solr_quickstart
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - lasso_python
  nexus:
    container_name: lasso-nexus
    image: klo2k/nexus3
    ports:
      - "8081:8081"